sql_temp_table_update_queries = {
    'incident_release_wise': """
	                        -- SQL query for update temp_incident_release_wise
                            BEGIN;
	                        INSERT INTO temp_incident_release_wise (
                                incident_id,
                                severity_id,
                                detected_release_id,
                                priority_id,
                                project_id,
                                status_id,
                                type_id,
                                opener_id,
                                owner_id,
                                incident_name,
                                resolved_release_id,
                                description,
                                verified_release_id,
                                creation_date,
                                last_update_date,
                                is_attachments,
                                completion_percent,
                                is_deleted,
                                component_ids,
                                priority_name,
                                priority_color,
                                severity_name,
                                severity_color,
                                status_name,
                                is_open_status,
                                type_name,
                                opener_name,
                                owner_name,
                                detected_release_version_number,
                                resolved_release_version_number,
                                verified_release_version_number,
                                project_is_active,
                                project_group_id,
                                incident_type_is_issue,
                                incident_type_is_risk,
                                project_name,
                                custom_02,
                                custom_04,
                                custom_08,
                                custom_11,
                                custom_12,
                                custom_13,
                                custom_14,
                                custom_15,
                                custom_16,
                                concurrency_date,
                                artifact_prefix,
                                artifact_type,
                                artifact_token,
                                incident_artifact_id,
                                properties,
                                component_names,
                                custom_property_alias,
                                custom_property_name,
                                custom_property_type,
                                incident_resolution_resolut,
                                incident_resolution_id,
                                incident_resolution_creator_id,
                                incident_resolution_resolution,
                                incident_resolution_creation_date,
                                incident_resolution_incident,
                                incident_resolution_creator,
                                incident_resolution_creator_name,
                                incident_resolution_properties,
                                artifact_link_id,
                                artifact_id,
                                artifact_type_id,
                                artifact_creator_id,
                                artifact_creation_date,
                                artifact_name,
                                artifact_type_name,
                                artifact_creator_name,
                                artifact_link_type_id,
                                artifact_link_type_name,
                                artifact_status_name,
                                artifact_project_id,
                                artifact_properties)
                            SELECT DISTINCT
                                "Report_IncidentData_Incident_IncidentId",
                                "Report_IncidentData_Incident_SeverityId",
                                "Report_IncidentData_Incident_DetectedReleaseId",
                                "Report_IncidentData_Incident_PriorityId",
                                "Report_IncidentData_Incident_ProjectId",
                                "Report_IncidentData_Incident_IncidentStatusId",
                                "Report_IncidentData_Incident_IncidentTypeId",
                                "Report_IncidentData_Incident_OpenerId",
                                "Report_IncidentData_Incident_OwnerId",
                                "Report_IncidentData_Incident_Name",
                                "Report_IncidentData_Incident_ResolvedReleaseId",
                                "Report_IncidentData_Incident_Description",
                                "Report_IncidentData_Incident_VerifiedReleaseId",
                                "Report_IncidentData_Incident_CreationDate",
                                "Report_IncidentData_Incident_LastUpdateDate",
                                "Report_IncidentData_Incident_IsAttachments",
                                "Report_IncidentData_Incident_CompletionPercent",
                                "Report_IncidentData_Incident_IsDeleted",
                                "Report_IncidentData_Incident_ComponentIds",
                                "Report_IncidentData_Incident_PriorityName",
                                "Report_IncidentData_Incident_PriorityColor",
                                "Report_IncidentData_Incident_SeverityName",
                                "Report_IncidentData_Incident_SeverityColor",
                                "Report_IncidentData_Incident_IncidentStatusName",
                                "Report_IncidentData_Incident_IncidentStatusIsOpenStatus",
                                "Report_IncidentData_Incident_IncidentTypeName",
                                "Report_IncidentData_Incident_OpenerName",
                                "Report_IncidentData_Incident_OwnerName",
                                "Report_IncidentData_Incident_DetectedReleaseVersionNumber",
                                "Report_IncidentData_Incident_ResolvedReleaseVersionNumber",
                                "Report_IncidentData_Incident_VerifiedReleaseVersionNumber",
                                "Report_IncidentData_Incident_ProjectIsActive",
                                "Report_IncidentData_Incident_ProjectGroupId",
                                "Report_IncidentData_Incident_IncidentTypeIsIssue",
                                "Report_IncidentData_Incident_IncidentTypeIsRisk",
                                "Report_IncidentData_Incident_ProjectName",
                                "IncidentData_Incident_Custom_02",
                                "IncidentData_Incident_Custom_04",
                                "IncidentData_Incident_Custom_08",
                                "IncidentData_Incident_Custom_11",
                                "IncidentData_Incident_Custom_12",
                                "IncidentData_Incident_Custom_13",
                                "IncidentData_Incident_Custom_14",
                                "IncidentData_Incident_Custom_15",
                                "IncidentData_Incident_Custom_16",
                                "Report_IncidentData_Incident_ConcurrencyDate",
                                "Report_IncidentData_Incident_ArtifactPrefix",
                                "Report_IncidentData_Incident_ArtifactType",
                                "Report_IncidentData_Incident_ArtifactToken",
                                "Report_IncidentData_Incident_ArtifactId",
                                "Report_IncidentData_Incident_Properties",
                                "Report_IncidentData_Incident_ComponentNames",
                                "Incident_CustomProperties_CustomProperty_Alias",
                                "Incident_CustomProperties_CustomProperty_Name",
                                "Incident_CustomProperties_CustomProperty_Type",
                                "Incident_IncidentResolutions_IncidentResolution_IncidentResolut",
                                "Incident_IncidentResolutions_IncidentResolution_IncidentId",
                                "Incident_IncidentResolutions_IncidentResolution_CreatorId",
                                "Incident_IncidentResolutions_IncidentResolution_Resolution",
                                "Incident_IncidentResolutions_IncidentResolution_CreationDate",
                                "Incident_IncidentResolutions_IncidentResolution_Incident",
                                "Incident_IncidentResolutions_IncidentResolution_Creator",
                                "Incident_IncidentResolutions_IncidentResolution_CreatorName",
                                "Incident_IncidentResolutions_IncidentResolution_Properties",
                                "Incident_ArtifactLinks_ArtifactLink_ArtifactLinkId",
                                "Incident_ArtifactLinks_ArtifactLink_ArtifactId",
                                "Incident_ArtifactLinks_ArtifactLink_ArtifactTypeId",
                                "Incident_ArtifactLinks_ArtifactLink_CreatorId",
                                "Incident_ArtifactLinks_ArtifactLink_CreationDate",
                                "Incident_ArtifactLinks_ArtifactLink_ArtifactName",
                                "Incident_ArtifactLinks_ArtifactLink_ArtifactTypeName",
                                "Incident_ArtifactLinks_ArtifactLink_CreatorName",
                                "Incident_ArtifactLinks_ArtifactLink_ArtifactLinkTypeId",
                                "Incident_ArtifactLinks_ArtifactLink_ArtifactLinkTypeName",
                                "Incident_ArtifactLinks_ArtifactLink_ArtifactStatusName",
                                "Incident_ArtifactLinks_ArtifactLink_ProjectId",
                                "Incident_ArtifactLinks_ArtifactLink_Properties"
                            FROM incident_release_wise;
                            DROP TABLE incident_release_wise;
                            COMMIT;
	                        """,

    'requirements_release_wise': """
	                        -- SQL query for update temp_requirements_release_wise
                            BEGIN;
                            INSERT INTO temp_requirements_release_wise (
                                requirement_id,
                                author_id,
                                release_id,
                                project_id,
                                requirement_type_id,
                                requirement_status_id,
                                component_id,
                                importance_id,
                                requirement_name,
                                creation_date,
                                indent_level,
                                description,
                                last_update_date,
                                is_summary,
                                is_attachments,
                                coverage_count_total,
                                coverage_count_passed,
                                coverage_count_failed,
                                coverage_count_caution,
                                coverage_count_blocked,
                                task_count,
                                task_percent_on_time,
                                task_percent_late_finish,
                                task_percent_not_start,
                                task_percent_late_start,
                                is_deleted,
                                concurrency_date,
                                requirement_status_name,
                                requirement_type_name,
                                component_name,
                                author_name,
                                importance_name,
                                release_version_number,
                                is_expanded,
                                is_visible,
                                project_name,
                                project_is_active,
                                requirement_rank,
                                requirement_type_is_steps,
                                importance_color,
                                importance_score,
                                artifact_prefix,
                                artifact_type,
                                artifact_token,
                                artifact_id,
                                parent_indent_level,
                                properties)
                            SELECT DISTINCT 
                                "Report_RequirementData_Requirement_RequirementId",
                                "Report_RequirementData_Requirement_AuthorId",
                                "Report_RequirementData_Requirement_ReleaseId",
                                "Report_RequirementData_Requirement_ProjectId",
                                "Report_RequirementData_Requirement_RequirementTypeId",
                                "Report_RequirementData_Requirement_RequirementStatusId",
                                "Report_RequirementData_Requirement_ComponentId",
                                "Report_RequirementData_Requirement_ImportanceId",
                                "Report_RequirementData_Requirement_Name",
                                "Report_RequirementData_Requirement_CreationDate",
                                "Report_RequirementData_Requirement_IndentLevel",
                                "Report_RequirementData_Requirement_Description",
                                "Report_RequirementData_Requirement_LastUpdateDate",
                                "Report_RequirementData_Requirement_IsSummary",
                                "Report_RequirementData_Requirement_IsAttachments",
                                "Report_RequirementData_Requirement_CoverageCountTotal",
                                "Report_RequirementData_Requirement_CoverageCountPassed",
                                "Report_RequirementData_Requirement_CoverageCountFailed",
                                "Report_RequirementData_Requirement_CoverageCountCaution",
                                "Report_RequirementData_Requirement_CoverageCountBlocked",
                                "Report_RequirementData_Requirement_TaskCount",
                                "Report_RequirementData_Requirement_TaskPercentOnTime",
                                "Report_RequirementData_Requirement_TaskPercentLateFinish",
                                "Report_RequirementData_Requirement_TaskPercentNotStart",
                                "Report_RequirementData_Requirement_TaskPercentLateStart",
                                "Report_RequirementData_Requirement_IsDeleted",
                                "Report_RequirementData_Requirement_ConcurrencyDate",
                                "Report_RequirementData_Requirement_RequirementStatusName",
                                "Report_RequirementData_Requirement_RequirementTypeName",
                                "Report_RequirementData_Requirement_ComponentName",
                                "Report_RequirementData_Requirement_AuthorName",
                                "Report_RequirementData_Requirement_ImportanceName",
                                "Report_RequirementData_Requirement_ReleaseVersionNumber",
                                "Report_RequirementData_Requirement_IsExpanded",
                                "Report_RequirementData_Requirement_IsVisible",
                                "Report_RequirementData_Requirement_ProjectName",
                                "Report_RequirementData_Requirement_ProjectIsActive",
                                "Report_RequirementData_Requirement_Rank",
                                "Report_RequirementData_Requirement_RequirementTypeIsSteps",
                                "Report_RequirementData_Requirement_ImportanceColor",
                                "Report_RequirementData_Requirement_ImportanceScore",
                                "Report_RequirementData_Requirement_ArtifactPrefix",
                                "Report_RequirementData_Requirement_ArtifactType",
                                "Report_RequirementData_Requirement_ArtifactToken",
                                "Report_RequirementData_Requirement_ArtifactId",
                                "Report_RequirementData_Requirement_ParentIndentLevel",
                                "Report_RequirementData_Requirement_Properties"
                            FROM requirements_release_wise;
                            DROP TABLE requirements_release_wise;
                            COMMIT;
                        """,
        
    'requirements_components_wise': """
	                        -- SQL query for update temp_requirements_components_wise
                            BEGIN;
                            INSERT INTO temp_requirements_components_wise (
                                requirement_id,
                                requirement_name,
                                author_id,
                                release_id,
                                project_id,
                                requirement_type_id,
                                requirement_status_id,
                                component_id,
                                importance_id,
                                creation_date,
                                indent_level,
                                description,
                                last_update_date,
                                is_summary,
                                is_attachments,
                                coverage_count_total,
                                coverage_count_passed,
                                coverage_count_failed,
                                coverage_count_caution,
                                coverage_count_blocked,
                                task_count,
                                task_percent_on_time,
                                task_percent_late_finish,
                                task_percent_not_start,
                                task_percent_late_start,
                                is_deleted,
                                concurrency_date,
                                requirement_status_name,
                                requirement_type_name,
                                component_name,
                                author_name,
                                importance_name,
                                release_version_number,
                                is_expanded,
                                is_visible,
                                project_name,
                                project_is_active,
                                requirement_rank,
                                requirement_type_is_steps,
                                importance_color,
                                importance_score,
                                artifact_prefix,
                                artifact_type,
                                artifact_token,
                                artifact_id,
                                parent_indent_level,
                                properties,
                                test_case_id)
                            SELECT DISTINCT
                                "Report_RequirementData_Requirement_RequirementId",
                                "Report_RequirementData_Requirement_Name",
                                "Report_RequirementData_Requirement_AuthorId",
                                "Report_RequirementData_Requirement_ReleaseId",
                                "Report_RequirementData_Requirement_ProjectId",
                                "Report_RequirementData_Requirement_RequirementTypeId",
                                "Report_RequirementData_Requirement_RequirementStatusId",
                                "Report_RequirementData_Requirement_ComponentId",
                                "Report_RequirementData_Requirement_ImportanceId",
                                "Report_RequirementData_Requirement_CreationDate",
                                "Report_RequirementData_Requirement_IndentLevel",
                                "Report_RequirementData_Requirement_Description",
                                "Report_RequirementData_Requirement_LastUpdateDate",
                                "Report_RequirementData_Requirement_IsSummary",
                                "Report_RequirementData_Requirement_IsAttachments",
                                "Report_RequirementData_Requirement_CoverageCountTotal",
                                "Report_RequirementData_Requirement_CoverageCountPassed",
                                "Report_RequirementData_Requirement_CoverageCountFailed",
                                "Report_RequirementData_Requirement_CoverageCountCaution",
                                "Report_RequirementData_Requirement_CoverageCountBlocked",
                                "Report_RequirementData_Requirement_TaskCount",
                                "Report_RequirementData_Requirement_TaskPercentOnTime",
                                "Report_RequirementData_Requirement_TaskPercentLateFinish",
                                "Report_RequirementData_Requirement_TaskPercentNotStart",
                                "Report_RequirementData_Requirement_TaskPercentLateStart",
                                "Report_RequirementData_Requirement_IsDeleted",
                                "Report_RequirementData_Requirement_ConcurrencyDate",
                                "Report_RequirementData_Requirement_RequirementStatusName",
                                "Report_RequirementData_Requirement_RequirementTypeName",
                                "Report_RequirementData_Requirement_ComponentName",
                                "Report_RequirementData_Requirement_AuthorName",
                                "Report_RequirementData_Requirement_ImportanceName",
                                "Report_RequirementData_Requirement_ReleaseVersionNumber",
                                "Report_RequirementData_Requirement_IsExpanded",
                                "Report_RequirementData_Requirement_IsVisible",
                                "Report_RequirementData_Requirement_ProjectName",
                                "Report_RequirementData_Requirement_ProjectIsActive",
                                "Report_RequirementData_Requirement_Rank",
                                "Report_RequirementData_Requirement_RequirementTypeIsSteps",
                                "Report_RequirementData_Requirement_ImportanceColor",
                                "Report_RequirementData_Requirement_ImportanceScore",
                                "Report_RequirementData_Requirement_ArtifactPrefix",
                                "Report_RequirementData_Requirement_ArtifactType",
                                "Report_RequirementData_Requirement_ArtifactToken",
                                "Report_RequirementData_Requirement_ArtifactId",
                                "Report_RequirementData_Requirement_ParentIndentLevel",
                                "Report_RequirementData_Requirement_Properties",
                                "Requirement_TestCases_TestCase_TestCaseId"
                            FROM requirements_components_wise;
                            DROP TABLE requirements_components_wise;
                            COMMIT;
                        """,

    'test_case_release_wise': """
                            -- SQL query for update temp_test_case_release_wise
                            BEGIN;
                            CREATE TABLE temp_table AS SELECT * FROM test_case_release_wise WHERE "TestCase_Requirements_Requirement_RequirementId" IS NOT NULL;
                            INSERT INTO temp_test_case_release_wise (
                                test_case_folder_Id,
                                parent_test_case_folder_Id,
                                test_case_folder_project_id,
                                test_case_folder_name,
                                test_case_folder_description,
                                test_case_folder_execution_date,
                                test_case_folder_last_update_date,
                                test_case_folder_estimated_duration,
                                test_case_folder_actual_duration,
                                test_case_folder_count_passed,
                                test_case_folder_count_failed,
                                test_case_folder_count_blocked,
                                test_case_folder_count_caution,
                                test_case_folder_count_not_run,
                                test_case_folder_count_not_applicable,
                                test_case_folder_artifact_prefix,
                                test_case_folder_artifact_type,
                                test_case_folder_artifact_token,
                                test_case_folder_artifact_id,
                                test_case_folder_execution_status_id,
                                test_case_folder_test_case_count,
                                test_case_folder_properties,
                                test_case_folder_indent_level,
                                test_case_id,
                                test_case_priority_id,
                                test_case_project_id,
                                test_case_author_id,
                                test_case_status_id,
                                test_case_type_id,
                                test_case_test_case_folder_id,
                                test_case_name,
                                test_case_owner_id,
                                test_case_description,
                                test_case_creation_date,
                                test_case_last_update_date,
                                test_case_is_attachments,
                                test_case_is_test_steps,
                                test_case_is_deleted,
                                test_case_concurrency_date,
                                test_case_component_ids,
                                test_case_execution_status_id,
                                test_case_execution_date,
                                test_case_actual_duration,
                                test_case_release_id,
                                test_case_execution_status_name,
                                test_case_priority_name,
                                test_case_author_name,
                                test_case_owner_name,
                                test_case_status_name,
                                test_case_type_name,
                                test_case_priority_color,
                                test_case_artifact_prefix,
                                test_case_artifact_type,
                                test_case_artifact_token,
                                test_case_artifact_id,
                                test_case_is_active,
                                test_case_properties,
                                test_case_component_names,
                                requirement_id)
                            SELECT DISTINCT
                                "Report_TestCaseData_TestCaseFolder_TestCaseFolderId" AS test_case_folder_Id,
                                "Report_TestCaseData_TestCaseFolder_ParentTestCaseFolderId" AS parent_test_case_folder_Id,
                                "Report_TestCaseData_TestCaseFolder_ProjectId" AS test_case_folder_project_id,
                                "Report_TestCaseData_TestCaseFolder_Name" AS test_case_folder_name,
                                "Report_TestCaseData_TestCaseFolder_Description" AS test_case_folder_description,
                                "Report_TestCaseData_TestCaseFolder_ExecutionDate" AS test_case_folder_execution_date,
                                "Report_TestCaseData_TestCaseFolder_LastUpdateDate" AS test_case_folder_last_update_date,
                                "Report_TestCaseData_TestCaseFolder_EstimatedDuration" AS test_case_folder_estimated_duration,
                                "Report_TestCaseData_TestCaseFolder_ActualDuration" AS test_case_folder_actual_duration,
                                "Report_TestCaseData_TestCaseFolder_CountPassed" AS test_case_folder_count_passed,
                                "Report_TestCaseData_TestCaseFolder_CountFailed" AS test_case_folder_count_failed,
                                "Report_TestCaseData_TestCaseFolder_CountBlocked" AS test_case_folder_count_blocked,
                                "Report_TestCaseData_TestCaseFolder_CountCaution" AS test_case_folder_count_caution,
                                "Report_TestCaseData_TestCaseFolder_CountNotRun" AS test_case_folder_count_not_run,
                                "Report_TestCaseData_TestCaseFolder_CountNotApplicable" AS test_case_folder_count_not_applicable,
                                "Report_TestCaseData_TestCaseFolder_ArtifactPrefix" AS test_case_folder_artifact_prefix,
                                "Report_TestCaseData_TestCaseFolder_ArtifactType" AS test_case_folder_artifact_type,
                                "Report_TestCaseData_TestCaseFolder_ArtifactToken" AS test_case_folder_artifact_token,
                                "Report_TestCaseData_TestCaseFolder_ArtifactId" AS test_case_folder_artifact_id,
                                "Report_TestCaseData_TestCaseFolder_ExecutionStatusId" AS test_case_folder_execution_status_id,
                                "Report_TestCaseData_TestCaseFolder_TestCaseCount" AS test_case_folder_test_case_count,
                                "Report_TestCaseData_TestCaseFolder_Properties" AS test_case_folder_properties,
                                "Report_TestCaseData_TestCaseFolder_IndentLevel" AS test_case_folder_indent_level,
                                "TestCaseFolder_TestCases_TestCase_TestCaseId" AS test_case_id,
                                "TestCaseFolder_TestCases_TestCase_TestCasePriorityId" AS test_case_priority_id,
                                "TestCaseFolder_TestCases_TestCase_ProjectId" AS test_case_project_id,
                                "TestCaseFolder_TestCases_TestCase_AuthorId" AS test_case_author_id,
                                "TestCaseFolder_TestCases_TestCase_TestCaseStatusId" AS test_case_status_id,
                                "TestCaseFolder_TestCases_TestCase_TestCaseTypeId" AS test_case_type_id,
                                "TestCaseFolder_TestCases_TestCase_TestCaseFolderId" AS test_case_test_case_folder_id,
                                "TestCaseFolder_TestCases_TestCase_Name" AS test_case_name,
                                "TestCaseFolder_TestCases_TestCase_OwnerId" AS test_case_owner_id,
                                "TestCaseFolder_TestCases_TestCase_Description" AS test_case_description,
                                "TestCaseFolder_TestCases_TestCase_CreationDate" AS test_case_creation_date,
                                "TestCaseFolder_TestCases_TestCase_LastUpdateDate" AS test_case_last_update_date,
                                "TestCaseFolder_TestCases_TestCase_IsAttachments" AS test_case_is_attachments,
                                "TestCaseFolder_TestCases_TestCase_IsTestSteps" AS test_case_is_test_steps,
                                "TestCaseFolder_TestCases_TestCase_IsDeleted" AS test_case_is_deleted,
                                "TestCaseFolder_TestCases_TestCase_ConcurrencyDate" AS test_case_concurrency_date,
                                "TestCaseFolder_TestCases_TestCase_ComponentIds" AS test_case_component_ids,
                                "TestCaseFolder_TestCases_TestCase_ExecutionStatusId" AS test_case_execution_status_id,
                                "TestCaseFolder_TestCases_TestCase_ExecutionDate" AS test_case_execution_date,
                                "TestCaseFolder_TestCases_TestCase_ActualDuration" AS test_case_actual_duration,
                                "TestCaseFolder_TestCases_TestCase_ReleaseId" AS test_case_release_id,
                                "TestCaseFolder_TestCases_TestCase_ExecutionStatusName" AS test_case_execution_status_name,
                                "TestCaseFolder_TestCases_TestCase_TestCasePriorityName" AS test_case_priority_name,
                                "TestCaseFolder_TestCases_TestCase_AuthorName" AS test_case_author_name,
                                "TestCaseFolder_TestCases_TestCase_OwnerName" AS test_case_owner_name,
                                "TestCaseFolder_TestCases_TestCase_TestCaseStatusName" AS test_case_status_name,
                                "TestCaseFolder_TestCases_TestCase_TestCaseTypeName" AS test_case_type_name,
                                "TestCaseFolder_TestCases_TestCase_TestCasePriorityColor" AS test_case_priority_color,
                                "TestCaseFolder_TestCases_TestCase_ArtifactPrefix" AS test_case_artifact_prefix,
                                "TestCaseFolder_TestCases_TestCase_ArtifactType" AS test_case_artifact_type,
                                "TestCaseFolder_TestCases_TestCase_ArtifactToken" AS test_case_artifact_token,
                                "TestCaseFolder_TestCases_TestCase_ArtifactId" AS test_case_artifact_id,
                                "TestCaseFolder_TestCases_TestCase_IsActive" AS test_case_is_active,
                                "TestCaseFolder_TestCases_TestCase_Properties" AS test_case_properties,
                                "TestCaseFolder_TestCases_TestCase_ComponentNames" AS test_case_component_names,
                                "TestCase_Requirements_Requirement_RequirementId" AS requirement_id
                            FROM temp_table;
                            DROP TABLE test_case_release_wise, temp_table;
                            COMMIT;
                        """,

    'test_run_release_wise': """
                            -- SQL query for update temp_test_run_release_wise
                            BEGIN;
                            CREATE TABLE temp_table AS SELECT * FROM test_run_release_wise WHERE "Report_TestRunData_TestRun_TestCaseId" IS NOT NULL;
                            INSERT INTO temp_test_run_release_wise (
                                test_run_id,
                                test_case_id,
                                test_run_type_id,
                                release_id,
                                test_set_id,
                                test_set_test_case_id,
                                tester_id,
                                test_runs_pending_id,
                                execution_status_id,
                                start_date,
                                test_run_name,
                                description,
                                end_date,
                                actual_duration,
                                is_attachments,
                                is_deleted,
                                concurrency_date,
                                execution_status_name,
                                tester_name,
                                release_name,
                                release_version_number,
                                test_set_name,
                                test_run_type_name,
                                project_id,
                                change_set_id,
                                artifact_prefix,
                                artifact_type,
                                artifact_token,
                                artifact_id,
                                properties)
                            SELECT DISTINCT
                                "Report_TestRunData_TestRun_TestRunId" AS test_run_id,
                                "Report_TestRunData_TestRun_TestCaseId" AS test_case_id,
                                "Report_TestRunData_TestRun_TestRunTypeId" AS test_run_type_id,
                                "Report_TestRunData_TestRun_ReleaseId" AS release_id,
                                "Report_TestRunData_TestRun_TestSetId" AS test_set_id,
                                "Report_TestRunData_TestRun_TestSetTestCaseId" AS test_set_test_case_id,
                                "Report_TestRunData_TestRun_TesterId" AS tester_id,
                                "Report_TestRunData_TestRun_TestRunsPendingId" AS test_runs_pending_id,
                                "Report_TestRunData_TestRun_ExecutionStatusId" AS execution_status_id,
                                "Report_TestRunData_TestRun_StartDate" AS start_date,
                                "Report_TestRunData_TestRun_Name" AS test_run_name,
                                "Report_TestRunData_TestRun_Description" AS description,
                                "Report_TestRunData_TestRun_EndDate" AS end_date,
                                "Report_TestRunData_TestRun_ActualDuration" AS actual_duration,
                                "Report_TestRunData_TestRun_IsAttachments" AS is_attachments,
                                "Report_TestRunData_TestRun_IsDeleted" AS is_deleted,
                                "Report_TestRunData_TestRun_ConcurrencyDate" AS concurrency_date,
                                "Report_TestRunData_TestRun_ExecutionStatusName" AS execution_status_name,
                                "Report_TestRunData_TestRun_TesterName" AS tester_name,
                                "Report_TestRunData_TestRun_ReleaseName" AS release_name,
                                "Report_TestRunData_TestRun_ReleaseVersionNumber" AS release_version_number,
                                "Report_TestRunData_TestRun_TestSetName" AS test_set_name,
                                "Report_TestRunData_TestRun_TestRunTypeName" AS test_run_type_name,
                                "Report_TestRunData_TestRun_ProjectId" AS project_id,
                                "Report_TestRunData_TestRun_ChangeSetId" AS change_set_id,
                                "Report_TestRunData_TestRun_ArtifactPrefix" AS artifact_prefix,
                                "Report_TestRunData_TestRun_ArtifactType" AS artifact_type,
                                "Report_TestRunData_TestRun_ArtifactToken" AS artifact_token,
                                "Report_TestRunData_TestRun_ArtifactId" AS artifact_id,
                                "Report_TestRunData_TestRun_Properties" AS properties
                            FROM temp_table;
                            DROP TABLE test_run_release_wise, temp_table;
                            COMMIT;
                        """,
                        
    # 'test_set_release_wise': """
    #                         -- SQL query for test_set_release_wise_updated
    #                         BEGIN;
    #                         INSERT INTO test_set_release_wise_updated (
                            
    #                         )
    #                         SELECT

    #                         FROM test_set_release_wise WHERE test_case_id IS NOT NULL;
    #                         DROP TABLE test_set_release_wise;
    #                         COMMIT;
    #                     """,                   
	    
}


sql_history_update_queries = {

    'incident_release_wise': """
	                            -- SQL query for update histry_incident_release_wise
                                BEGIN;
                                INSERT INTO histry_incident_release_wise (		
                                    incident_id,
                                    severity_id,
                                    detected_release_id,
                                    priority_id,
                                    project_id,
                                    status_id,
                                    type_id,
                                    opener_id,
                                    owner_id,
                                    incident_name,
                                    resolved_release_id,
                                    description,
                                    verified_release_id,
                                    creation_date,
                                    last_update_date,
                                    is_attachments,
                                    completion_percent,
                                    is_deleted,
                                    component_ids,
                                    priority_name,
                                    priority_color,
                                    severity_name,
                                    severity_color,
                                    status_name,
                                    is_open_status,
                                    type_name,
                                    opener_name,
                                    owner_name,
                                    detected_release_version_number,
                                    resolved_release_version_number,
                                    verified_release_version_number,
                                    project_is_active,
                                    project_group_id,
                                    incident_type_is_issue,
                                    incident_type_is_risk,
                                    project_name,
                                    custom_02,
                                    custom_04,
                                    custom_08,
                                    custom_11,
                                    custom_12,
                                    custom_13,
                                    custom_14,
                                    custom_15,
                                    custom_16,
                                    concurrency_date,
                                    artifact_prefix,
                                    artifact_type,
                                    artifact_token,
                                    incident_artifact_id,
                                    properties,
                                    component_names,
                                    custom_property_alias,
                                    custom_property_name,
                                    custom_property_type,
                                    incident_resolution_resolut,
                                    incident_resolution_id,
                                    incident_resolution_creator_id,
                                    incident_resolution_resolution,
                                    incident_resolution_creation_date,
                                    incident_resolution_incident,
                                    incident_resolution_creator,
                                    incident_resolution_creator_name,
                                    incident_resolution_properties,
                                    artifact_link_id,
                                    artifact_id,
                                    artifact_type_id,
                                    artifact_creator_id,
                                    artifact_creation_date,
                                    artifact_name,
                                    artifact_type_name,
                                    artifact_creator_name,
                                    artifact_link_type_id,
                                    artifact_link_type_name,
                                    artifact_status_name,
                                    artifact_project_id,
                                    artifact_properties,
                                    updated_version, 
                                    updated_date_time)
						        SELECT DISTINCT
                                    incident_id,
                                    severity_id,
                                    detected_release_id,
                                    priority_id,
                                    project_id,
                                    status_id,
                                    type_id,
                                    opener_id,
                                    owner_id,
                                    incident_name,
                                    resolved_release_id,
                                    description,
                                    verified_release_id,
                                    creation_date,
                                    last_update_date,
                                    is_attachments,
                                    completion_percent,
                                    is_deleted,
                                    component_ids,
                                    priority_name,
                                    priority_color,
                                    severity_name,
                                    severity_color,
                                    status_name,
                                    is_open_status,
                                    type_name,
                                    opener_name,
                                    owner_name,
                                    detected_release_version_number,
                                    resolved_release_version_number,
                                    verified_release_version_number,
                                    project_is_active,
                                    project_group_id,
                                    incident_type_is_issue,
                                    incident_type_is_risk,
                                    project_name,
                                    custom_02,
                                    custom_04,
                                    custom_08,
                                    custom_11,
                                    custom_12,
                                    custom_13,
                                    custom_14,
                                    custom_15,
                                    custom_16,
                                    concurrency_date,
                                    artifact_prefix,
                                    artifact_type,
                                    artifact_token,
                                    incident_artifact_id,
                                    properties,
                                    component_names,
                                    custom_property_alias,
                                    custom_property_name,
                                    custom_property_type,
                                    incident_resolution_resolut,
                                    incident_resolution_id,
                                    incident_resolution_creator_id,
                                    incident_resolution_resolution,
                                    incident_resolution_creation_date,
                                    incident_resolution_incident,
                                    incident_resolution_creator,
                                    incident_resolution_creator_name,
                                    incident_resolution_properties,
                                    artifact_link_id,
                                    artifact_id,
                                    artifact_type_id,
                                    artifact_creator_id,
                                    artifact_creation_date,
                                    artifact_name,
                                    artifact_type_name,
                                    artifact_creator_name,
                                    artifact_link_type_id,
                                    artifact_link_type_name,
                                    artifact_status_name,
                                    artifact_project_id,
                                    artifact_properties,
                                    %s, 
								    CURRENT_TIMESTAMP
                                FROM incident_release_wise_updated;
                                DELETE FROM incident_release_wise_updated;
                                COMMIT;
                            """,

    'requirements_release_wise': """z
	                            -- SQL query for update histry_requirements_release_wise
                                BEGIN;
                                INSERT INTO histry_requirements_release_wise (		
                                    requirement_id,
                                    author_id,
                                    release_id,
                                    project_id,
                                    requirement_type_id,
                                    requirement_status_id,
                                    component_id,
                                    importance_id,
                                    requirement_name,
                                    creation_date,
                                    indent_level,
                                    description,
                                    last_update_date,
                                    is_summary,
                                    is_attachments,
                                    coverage_count_total,
                                    coverage_count_passed,
                                    coverage_count_failed,
                                    coverage_count_caution,
                                    coverage_count_blocked,
                                    task_count,
                                    task_percent_on_time,
                                    task_percent_late_finish,
                                    task_percent_not_start,
                                    task_percent_late_start,
                                    is_deleted,
                                    concurrency_date,
                                    requirement_status_name,
                                    requirement_type_name,
                                    component_name,
                                    author_name,
                                    importance_name,
                                    release_version_number,
                                    is_expanded,
                                    is_visible,
                                    project_name,
                                    project_is_active,
                                    requirement_rank,
                                    requirement_type_is_steps,
                                    importance_color,
                                    importance_score,
                                    artifact_prefix,
                                    artifact_type,
                                    artifact_token,
                                    artifact_id,
                                    parent_indent_level,
                                    properties,
                                    updated_version, 
                                    updated_date_time)
						        SELECT DISTINCT
                                    requirement_id,
                                    author_id,
                                    release_id,
                                    project_id,
                                    requirement_type_id,
                                    requirement_status_id,
                                    component_id,
                                    importance_id,
                                    requirement_name,
                                    creation_date,
                                    indent_level,
                                    description,
                                    last_update_date,
                                    is_summary,
                                    is_attachments,
                                    coverage_count_total,
                                    coverage_count_passed,
                                    coverage_count_failed,
                                    coverage_count_caution,
                                    coverage_count_blocked,
                                    task_count,
                                    task_percent_on_time,
                                    task_percent_late_finish,
                                    task_percent_not_start,
                                    task_percent_late_start,
                                    is_deleted,
                                    concurrency_date,
                                    requirement_status_name,
                                    requirement_type_name,
                                    component_name,
                                    author_name,
                                    importance_name,
                                    release_version_number,
                                    is_expanded,
                                    is_visible,
                                    project_name,
                                    project_is_active,
                                    requirement_rank,
                                    requirement_type_is_steps,
                                    importance_color,
                                    importance_score,
                                    artifact_prefix,
                                    artifact_type,
                                    artifact_token,
                                    artifact_id,
                                    parent_indent_level,
                                    properties,
                                    %s, 
								    CURRENT_TIMESTAMP 
                                FROM requirements_release_wise_updated;
                                DELETE FROM requirements_release_wise_updated;
                                COMMIT;
                           """,

    'requirements_components_wise': """
	                            -- SQL query for update histry_requirements_components_wise
                                BEGIN;
                                INSERT INTO histry_requirements_components_wise (
                                	requirement_id,
                                    requirement_name,
                                    author_id,
                                    release_id,
                                    project_id,
                                    requirement_type_id,
                                    requirement_status_id,
                                    component_id,
                                    importance_id,
                                    creation_date,
                                    indent_level,
                                    description,
                                    last_update_date,
                                    is_summary,
                                    is_attachments,
                                    coverage_count_total,
                                    coverage_count_passed,
                                    coverage_count_failed,
                                    coverage_count_caution,
                                    coverage_count_blocked,
                                    task_count,
                                    task_percent_on_time,
                                    task_percent_late_finish,
                                    task_percent_not_start,
                                    task_percent_late_start,
                                    is_deleted,
                                    concurrency_date,
                                    requirement_status_name,
                                    requirement_type_name,
                                    component_name,
                                    author_name,
                                    importance_name,
                                    release_version_number,
                                    is_expanded,
                                    is_visible,
                                    project_name,
                                    project_is_active,
                                    requirement_rank,
                                    requirement_type_is_steps,
                                    importance_color,
                                    importance_score,
                                    artifact_prefix,
                                    artifact_type,
                                    artifact_token,
                                    artifact_id,
                                    parent_indent_level,
                                    properties,
                                    test_case_id,
                                    updated_version, 
                                    updated_date_time)
						        SELECT DISTINCT
                                    requirement_id,
                                    requirement_name,
                                    author_id,
                                    release_id,
                                    project_id,
                                    requirement_type_id,
                                    requirement_status_id,
                                    component_id,
                                    importance_id,
                                    creation_date,
                                    indent_level,
                                    description,
                                    last_update_date,
                                    is_summary,
                                    is_attachments,
                                    coverage_count_total,
                                    coverage_count_passed,
                                    coverage_count_failed,
                                    coverage_count_caution,
                                    coverage_count_blocked,
                                    task_count,
                                    task_percent_on_time,
                                    task_percent_late_finish,
                                    task_percent_not_start,
                                    task_percent_late_start,
                                    is_deleted,
                                    concurrency_date,
                                    requirement_status_name,
                                    requirement_type_name,
                                    component_name,
                                    author_name,
                                    importance_name,
                                    release_version_number,
                                    is_expanded,
                                    is_visible,
                                    project_name,
                                    project_is_active,
                                    requirement_rank,
                                    requirement_type_is_steps,
                                    importance_color,
                                    importance_score,
                                    artifact_prefix,
                                    artifact_type,
                                    artifact_token,
                                    artifact_id,
                                    parent_indent_level,
                                    properties,
                                    test_case_id,
                                    %s, 
								    CURRENT_TIMESTAMP
                                FROM requirements_components_wise_updated;
                                DELETE FROM requirements_components_wise_updated;
                                COMMIT;
                           """,

    'test_case_release_wise': """
	                            -- SQL query for update histry_test_case_release_wise
                                BEGIN;
                                INSERT INTO histry_test_case_release_wise (		
                                    test_case_folder_Id,
                                    parent_test_case_folder_Id,
                                    test_case_folder_project_id,
                                    test_case_folder_name,
                                    test_case_folder_description,
                                    test_case_folder_execution_date,
                                    test_case_folder_last_update_date,
                                    test_case_folder_estimated_duration,
                                    test_case_folder_actual_duration,
                                    test_case_folder_count_passed,
                                    test_case_folder_count_failed,
                                    test_case_folder_count_blocked,
                                    test_case_folder_count_caution,
                                    test_case_folder_count_not_run,
                                    test_case_folder_count_not_applicable,
                                    test_case_folder_artifact_prefix,
                                    test_case_folder_artifact_type,
                                    test_case_folder_artifact_token,
                                    test_case_folder_artifact_id,
                                    test_case_folder_execution_status_id,
                                    test_case_folder_test_case_count,
                                    test_case_folder_properties,
                                    test_case_folder_indent_level,
                                    test_case_id,
                                    test_case_priority_id,
                                    test_case_project_id,
                                    test_case_author_id,
                                    test_case_status_id,
                                    test_case_type_id,
                                    test_case_test_case_folder_id,
                                    test_case_name,
                                    test_case_owner_id,
                                    test_case_description,
                                    test_case_creation_date,
                                    test_case_last_update_date,
                                    test_case_is_attachments,
                                    test_case_is_test_steps,
                                    test_case_is_deleted,
                                    test_case_concurrency_date,
                                    test_case_component_ids,
                                    test_case_execution_status_id,
                                    test_case_execution_date,
                                    test_case_actual_duration,
                                    test_case_release_id,
                                    test_case_execution_status_name,
                                    test_case_priority_name,
                                    test_case_author_name,
                                    test_case_owner_name,
                                    test_case_status_name,
                                    test_case_type_name,
                                    test_case_priority_color,
                                    test_case_artifact_prefix,
                                    test_case_artifact_type,
                                    test_case_artifact_token,
                                    test_case_artifact_id,
                                    test_case_is_active,
                                    test_case_properties,
                                    test_case_component_names,
                                    requirement_id,
                                    updated_version, 
                                    updated_date_time)
						        SELECT DISTINCT
                                    test_case_folder_Id,
                                    parent_test_case_folder_Id,
                                    test_case_folder_project_id,
                                    test_case_folder_name,
                                    test_case_folder_description,
                                    test_case_folder_execution_date,
                                    test_case_folder_last_update_date,
                                    test_case_folder_estimated_duration,
                                    test_case_folder_actual_duration,
                                    test_case_folder_count_passed,
                                    test_case_folder_count_failed,
                                    test_case_folder_count_blocked,
                                    test_case_folder_count_caution,
                                    test_case_folder_count_not_run,
                                    test_case_folder_count_not_applicable,
                                    test_case_folder_artifact_prefix,
                                    test_case_folder_artifact_type,
                                    test_case_folder_artifact_token,
                                    test_case_folder_artifact_id,
                                    test_case_folder_execution_status_id,
                                    test_case_folder_test_case_count,
                                    test_case_folder_properties,
                                    test_case_folder_indent_level,
                                    test_case_id,
                                    test_case_priority_id,
                                    test_case_project_id,
                                    test_case_author_id,
                                    test_case_status_id,
                                    test_case_type_id,
                                    test_case_test_case_folder_id,
                                    test_case_name,
                                    test_case_owner_id,
                                    test_case_description,
                                    test_case_creation_date,
                                    test_case_last_update_date,
                                    test_case_is_attachments,
                                    test_case_is_test_steps,
                                    test_case_is_deleted,
                                    test_case_concurrency_date,
                                    test_case_component_ids,
                                    test_case_execution_status_id,
                                    test_case_execution_date,
                                    test_case_actual_duration,
                                    test_case_release_id,
                                    test_case_execution_status_name,
                                    test_case_priority_name,
                                    test_case_author_name,
                                    test_case_owner_name,
                                    test_case_status_name,
                                    test_case_type_name,
                                    test_case_priority_color,
                                    test_case_artifact_prefix,
                                    test_case_artifact_type,
                                    test_case_artifact_token,
                                    test_case_artifact_id,
                                    test_case_is_active,
                                    test_case_properties,
                                    test_case_component_names,
                                    requirement_id,
                                    %s, 
								    CURRENT_TIMESTAMP
                                FROM test_case_release_wise_updated;
                                DELETE FROM test_case_release_wise_updated;
                                COMMIT;
                           """,

    'test_run_release_wise': """
	                            -- SQL query for update histry_test_run_release_wise
                                BEGIN;
                                INSERT INTO histry_test_run_release_wise (		
                                    test_run_id,
                                    test_case_id,
                                    test_run_type_id,
                                    release_id,
                                    test_set_id,
                                    test_set_test_case_id,
                                    tester_id,
                                    test_runs_pending_id,
                                    execution_status_id,
                                    start_date,
                                    test_run_name,
                                    description,
                                    end_date,
                                    actual_duration,
                                    is_attachments,
                                    is_deleted,
                                    concurrency_date,
                                    execution_status_name,
                                    tester_name,
                                    release_name,
                                    release_version_number,
                                    test_set_name,
                                    test_run_type_name,
                                    project_id,
                                    change_set_id,
                                    artifact_prefix,
                                    artifact_type,
                                    artifact_token,
                                    artifact_id,
                                    properties,
                                    updated_version, 
                                    updated_date_time)
						        SELECT DISTINCT
                                    test_run_id,
                                    test_case_id,
                                    test_run_type_id,
                                    release_id,
                                    test_set_id,
                                    test_set_test_case_id,
                                    tester_id,
                                    test_runs_pending_id,
                                    execution_status_id,
                                    start_date,
                                    test_run_name,
                                    description,
                                    end_date,
                                    actual_duration,
                                    is_attachments,
                                    is_deleted,
                                    concurrency_date,
                                    execution_status_name,
                                    tester_name,
                                    release_name,
                                    release_version_number,
                                    test_set_name,
                                    test_run_type_name,
                                    project_id,
                                    change_set_id,
                                    artifact_prefix,
                                    artifact_type,
                                    artifact_token,
                                    artifact_id,
                                    properties,
                                    %s, 
								    CURRENT_TIMESTAMP
                                FROM test_run_release_wise_updated;
                                DELETE FROM test_run_release_wise_updated;
                                COMMIT;
                           """,

    # 'test_set_release_wise': """
	#                             -- SQL query for update histry_test_set_release_wise
    #                             BEGIN;
    #                             INSERT INTO histry_test_set_release_wise (		
    #                                 updated_version, 
    #                                 updated_date_time)
	# 					        SELECT DISTINCT
    #                                 %s, 
	# 							    CURRENT_TIMESTAMP
    #                             FROM test_set_release_wise_updated;
    #                             DELETE FROM test_set_release_wise_updated;
    #                             COMMIT;
    #                        """,

}


required_columns_dict = {
    'incident_release_wise': [
        "Report_IncidentData_Incident_IncidentId",
        "Report_IncidentData_Incident_SeverityId",
        "Report_IncidentData_Incident_DetectedReleaseId",
        "Report_IncidentData_Incident_PriorityId",
        "Report_IncidentData_Incident_ProjectId",
        "Report_IncidentData_Incident_IncidentStatusId",
        "Report_IncidentData_Incident_IncidentTypeId",
        "Report_IncidentData_Incident_OpenerId",
        "Report_IncidentData_Incident_OwnerId",
        "Report_IncidentData_Incident_Name",
        "Report_IncidentData_Incident_ResolvedReleaseId",
        "Report_IncidentData_Incident_Description",
        "Report_IncidentData_Incident_VerifiedReleaseId",
        "Report_IncidentData_Incident_CreationDate",
        "Report_IncidentData_Incident_LastUpdateDate",
        "Report_IncidentData_Incident_IsAttachments",
        "Report_IncidentData_Incident_CompletionPercent",
        "Report_IncidentData_Incident_IsDeleted",
        "Report_IncidentData_Incident_ComponentIds",
        "Report_IncidentData_Incident_PriorityName",
        "Report_IncidentData_Incident_PriorityColor",
        "Report_IncidentData_Incident_SeverityName",
        "Report_IncidentData_Incident_SeverityColor",
        "Report_IncidentData_Incident_IncidentStatusName",
        "Report_IncidentData_Incident_IncidentStatusIsOpenStatus",
        "Report_IncidentData_Incident_IncidentTypeName",
        "Report_IncidentData_Incident_OpenerName",
        "Report_IncidentData_Incident_OwnerName",
        "Report_IncidentData_Incident_DetectedReleaseVersionNumber",
        "Report_IncidentData_Incident_ResolvedReleaseVersionNumber",
        "Report_IncidentData_Incident_VerifiedReleaseVersionNumber",
        "Report_IncidentData_Incident_ProjectIsActive",
        "Report_IncidentData_Incident_ProjectGroupId",
        "Report_IncidentData_Incident_IncidentTypeIsIssue",
        "Report_IncidentData_Incident_IncidentTypeIsRisk",
        "Report_IncidentData_Incident_ProjectName",
        "IncidentData_Incident_Custom_02",
        "IncidentData_Incident_Custom_04",
        "IncidentData_Incident_Custom_08",
        "IncidentData_Incident_Custom_11",
        "IncidentData_Incident_Custom_12",
        "IncidentData_Incident_Custom_13",
        "IncidentData_Incident_Custom_14",
        "IncidentData_Incident_Custom_15",
        "IncidentData_Incident_Custom_16",
        "Report_IncidentData_Incident_ConcurrencyDate",
        "Report_IncidentData_Incident_ArtifactPrefix",
        "Report_IncidentData_Incident_ArtifactType",
        "Report_IncidentData_Incident_ArtifactToken",
        "Report_IncidentData_Incident_ArtifactId",
        "Report_IncidentData_Incident_Properties",
        "Report_IncidentData_Incident_ComponentNames",
        "Incident_CustomProperties_CustomProperty_Alias",
        "Incident_CustomProperties_CustomProperty_Name",
        "Incident_CustomProperties_CustomProperty_Type",
        "Incident_IncidentResolutions_IncidentResolution_IncidentResolut",
        "Incident_IncidentResolutions_IncidentResolution_IncidentId",
        "Incident_IncidentResolutions_IncidentResolution_CreatorId",
        "Incident_IncidentResolutions_IncidentResolution_Resolution",
        "Incident_IncidentResolutions_IncidentResolution_CreationDate",
        "Incident_IncidentResolutions_IncidentResolution_Incident",
        "Incident_IncidentResolutions_IncidentResolution_Creator",
        "Incident_IncidentResolutions_IncidentResolution_CreatorName",
        "Incident_IncidentResolutions_IncidentResolution_Properties",
        "Incident_ArtifactLinks_ArtifactLink_ArtifactLinkId",
        "Incident_ArtifactLinks_ArtifactLink_ArtifactId",
        "Incident_ArtifactLinks_ArtifactLink_ArtifactTypeId",
        "Incident_ArtifactLinks_ArtifactLink_CreatorId",
        "Incident_ArtifactLinks_ArtifactLink_CreationDate",
        "Incident_ArtifactLinks_ArtifactLink_ArtifactName",
        "Incident_ArtifactLinks_ArtifactLink_ArtifactTypeName",
        "Incident_ArtifactLinks_ArtifactLink_CreatorName",
        "Incident_ArtifactLinks_ArtifactLink_ArtifactLinkTypeId",
        "Incident_ArtifactLinks_ArtifactLink_ArtifactLinkTypeName",
        "Incident_ArtifactLinks_ArtifactLink_ArtifactStatusName",
        "Incident_ArtifactLinks_ArtifactLink_ProjectId",
        "Incident_ArtifactLinks_ArtifactLink_Properties"
    ],
    
    'requirements_release_wise': [
        "Report_RequirementData_Requirement_RequirementId",
        "Report_RequirementData_Requirement_AuthorId",
        "Report_RequirementData_Requirement_ReleaseId",
        "Report_RequirementData_Requirement_ProjectId",
        "Report_RequirementData_Requirement_RequirementTypeId",
        "Report_RequirementData_Requirement_RequirementStatusId",
        "Report_RequirementData_Requirement_ComponentId",
        "Report_RequirementData_Requirement_ImportanceId",
        "Report_RequirementData_Requirement_Name",
        "Report_RequirementData_Requirement_CreationDate",
        "Report_RequirementData_Requirement_IndentLevel",
        "Report_RequirementData_Requirement_Description",
        "Report_RequirementData_Requirement_LastUpdateDate",
        "Report_RequirementData_Requirement_IsSummary",
        "Report_RequirementData_Requirement_IsAttachments",
        "Report_RequirementData_Requirement_CoverageCountTotal",
        "Report_RequirementData_Requirement_CoverageCountPassed",
        "Report_RequirementData_Requirement_CoverageCountFailed",
        "Report_RequirementData_Requirement_CoverageCountCaution",
        "Report_RequirementData_Requirement_CoverageCountBlocked",
        "Report_RequirementData_Requirement_TaskCount",
        "Report_RequirementData_Requirement_TaskPercentOnTime",
        "Report_RequirementData_Requirement_TaskPercentLateFinish",
        "Report_RequirementData_Requirement_TaskPercentNotStart",
        "Report_RequirementData_Requirement_TaskPercentLateStart",
        "Report_RequirementData_Requirement_IsDeleted",
        "Report_RequirementData_Requirement_ConcurrencyDate",
        "Report_RequirementData_Requirement_RequirementStatusName",
        "Report_RequirementData_Requirement_RequirementTypeName",
        "Report_RequirementData_Requirement_ComponentName",
        "Report_RequirementData_Requirement_AuthorName",
        "Report_RequirementData_Requirement_ImportanceName",
        "Report_RequirementData_Requirement_ReleaseVersionNumber",
        "Report_RequirementData_Requirement_IsExpanded",
        "Report_RequirementData_Requirement_IsVisible",
        "Report_RequirementData_Requirement_ProjectName",
        "Report_RequirementData_Requirement_ProjectIsActive",
        "Report_RequirementData_Requirement_Rank",
        "Report_RequirementData_Requirement_RequirementTypeIsSteps",
        "Report_RequirementData_Requirement_ImportanceColor",
        "Report_RequirementData_Requirement_ImportanceScore",
        "Report_RequirementData_Requirement_ArtifactPrefix",
        "Report_RequirementData_Requirement_ArtifactType",
        "Report_RequirementData_Requirement_ArtifactToken",
        "Report_RequirementData_Requirement_ArtifactId",
        "Report_RequirementData_Requirement_ParentIndentLevel",
        "Report_RequirementData_Requirement_Properties"
    ],
    
    'requirements_components_wise' : [
        "Report_RequirementData_Requirement_RequirementId",
        "Report_RequirementData_Requirement_Name",
        "Report_RequirementData_Requirement_AuthorId",
        "Report_RequirementData_Requirement_ReleaseId",
        "Report_RequirementData_Requirement_ProjectId",
        "Report_RequirementData_Requirement_RequirementTypeId",
        "Report_RequirementData_Requirement_RequirementStatusId",
        "Report_RequirementData_Requirement_ComponentId",
        "Report_RequirementData_Requirement_ImportanceId",
        "Report_RequirementData_Requirement_CreationDate",
        "Report_RequirementData_Requirement_IndentLevel",
        "Report_RequirementData_Requirement_Description",
        "Report_RequirementData_Requirement_LastUpdateDate",
        "Report_RequirementData_Requirement_IsSummary",
        "Report_RequirementData_Requirement_IsAttachments",
        "Report_RequirementData_Requirement_CoverageCountTotal",
        "Report_RequirementData_Requirement_CoverageCountPassed",
        "Report_RequirementData_Requirement_CoverageCountFailed",
        "Report_RequirementData_Requirement_CoverageCountCaution",
        "Report_RequirementData_Requirement_CoverageCountBlocked",
        "Report_RequirementData_Requirement_TaskCount",
        "Report_RequirementData_Requirement_TaskPercentOnTime",
        "Report_RequirementData_Requirement_TaskPercentLateFinish",
        "Report_RequirementData_Requirement_TaskPercentNotStart",
        "Report_RequirementData_Requirement_TaskPercentLateStart",
        "Report_RequirementData_Requirement_IsDeleted",
        "Report_RequirementData_Requirement_ConcurrencyDate",
        "Report_RequirementData_Requirement_RequirementStatusName",
        "Report_RequirementData_Requirement_RequirementTypeName",
        "Report_RequirementData_Requirement_ComponentName",
        "Report_RequirementData_Requirement_AuthorName",
        "Report_RequirementData_Requirement_ImportanceName",
        "Report_RequirementData_Requirement_ReleaseVersionNumber",
        "Report_RequirementData_Requirement_IsExpanded",
        "Report_RequirementData_Requirement_IsVisible",
        "Report_RequirementData_Requirement_ProjectName",
        "Report_RequirementData_Requirement_ProjectIsActive",
        "Report_RequirementData_Requirement_Rank",
        "Report_RequirementData_Requirement_RequirementTypeIsSteps",
        "Report_RequirementData_Requirement_ImportanceColor",
        "Report_RequirementData_Requirement_ImportanceScore",
        "Report_RequirementData_Requirement_ArtifactPrefix",
        "Report_RequirementData_Requirement_ArtifactType",
        "Report_RequirementData_Requirement_ArtifactToken",
        "Report_RequirementData_Requirement_ArtifactId",
        "Report_RequirementData_Requirement_ParentIndentLevel",
        "Report_RequirementData_Requirement_Properties",
        "Requirement_TestCases_TestCase_TestCaseId"
    ],

    'test_case_release_wise' : [
        "Report_TestCaseData_TestCaseFolder_TestCaseFolderId",
        "Report_TestCaseData_TestCaseFolder_ParentTestCaseFolderId",
        "Report_TestCaseData_TestCaseFolder_ProjectId",
        "Report_TestCaseData_TestCaseFolder_Name",
        "Report_TestCaseData_TestCaseFolder_Description",
        "Report_TestCaseData_TestCaseFolder_ExecutionDate",
        "Report_TestCaseData_TestCaseFolder_LastUpdateDate",
        "Report_TestCaseData_TestCaseFolder_EstimatedDuration",
        "Report_TestCaseData_TestCaseFolder_ActualDuration",
        "Report_TestCaseData_TestCaseFolder_CountPassed",
        "Report_TestCaseData_TestCaseFolder_CountFailed",
        "Report_TestCaseData_TestCaseFolder_CountBlocked",
        "Report_TestCaseData_TestCaseFolder_CountCaution",
        "Report_TestCaseData_TestCaseFolder_CountNotRun",
        "Report_TestCaseData_TestCaseFolder_CountNotApplicable",
        "Report_TestCaseData_TestCaseFolder_ArtifactPrefix",
        "Report_TestCaseData_TestCaseFolder_ArtifactType",
        "Report_TestCaseData_TestCaseFolder_ArtifactToken",
        "Report_TestCaseData_TestCaseFolder_ArtifactId",
        "Report_TestCaseData_TestCaseFolder_ExecutionStatusId",
        "Report_TestCaseData_TestCaseFolder_TestCaseCount",
        "Report_TestCaseData_TestCaseFolder_Properties",
        "Report_TestCaseData_TestCaseFolder_IndentLevel",
        "TestCaseFolder_TestCases_TestCase_TestCaseId",
        "TestCaseFolder_TestCases_TestCase_TestCasePriorityId",
        "TestCaseFolder_TestCases_TestCase_ProjectId",
        "TestCaseFolder_TestCases_TestCase_AuthorId",
        "TestCaseFolder_TestCases_TestCase_TestCaseStatusId",
        "TestCaseFolder_TestCases_TestCase_TestCaseTypeId",
        "TestCaseFolder_TestCases_TestCase_TestCaseFolderId",
        "TestCaseFolder_TestCases_TestCase_Name",
        "TestCaseFolder_TestCases_TestCase_OwnerId",
        "TestCaseFolder_TestCases_TestCase_Description",
        "TestCaseFolder_TestCases_TestCase_CreationDate",
        "TestCaseFolder_TestCases_TestCase_LastUpdateDate",
        "TestCaseFolder_TestCases_TestCase_IsAttachments",
        "TestCaseFolder_TestCases_TestCase_IsTestSteps",
        "TestCaseFolder_TestCases_TestCase_IsDeleted",
        "TestCaseFolder_TestCases_TestCase_ConcurrencyDate",
        "TestCaseFolder_TestCases_TestCase_ComponentIds",
        "TestCaseFolder_TestCases_TestCase_ExecutionStatusId",
        "TestCaseFolder_TestCases_TestCase_ExecutionDate",
        "TestCaseFolder_TestCases_TestCase_ActualDuration",
        "TestCaseFolder_TestCases_TestCase_ReleaseId",
        "TestCaseFolder_TestCases_TestCase_ExecutionStatusName",
        "TestCaseFolder_TestCases_TestCase_TestCasePriorityName",
        "TestCaseFolder_TestCases_TestCase_AuthorName",
        "TestCaseFolder_TestCases_TestCase_OwnerName",
        "TestCaseFolder_TestCases_TestCase_TestCaseStatusName",
        "TestCaseFolder_TestCases_TestCase_TestCaseTypeName",
        "TestCaseFolder_TestCases_TestCase_TestCasePriorityColor",
        "TestCaseFolder_TestCases_TestCase_ArtifactPrefix",
        "TestCaseFolder_TestCases_TestCase_ArtifactType",
        "TestCaseFolder_TestCases_TestCase_ArtifactToken",
        "TestCaseFolder_TestCases_TestCase_ArtifactId",
        "TestCaseFolder_TestCases_TestCase_IsActive",
        "TestCaseFolder_TestCases_TestCase_Properties",
        "TestCaseFolder_TestCases_TestCase_ComponentNames",
        "TestCase_Requirements_Requirement_RequirementId"               
    ],

    'test_run_release_wise' : [
        "Report_TestRunData_TestRun_TestRunId",
        "Report_TestRunData_TestRun_TestCaseId",
        "Report_TestRunData_TestRun_TestRunTypeId",
        "Report_TestRunData_TestRun_ReleaseId",
        "Report_TestRunData_TestRun_TestSetId",
        "Report_TestRunData_TestRun_TestSetTestCaseId",
        "Report_TestRunData_TestRun_TesterId",
        "Report_TestRunData_TestRun_TestRunsPendingId",
        "Report_TestRunData_TestRun_ExecutionStatusId",
        "Report_TestRunData_TestRun_StartDate",
        "Report_TestRunData_TestRun_Name",
        "Report_TestRunData_TestRun_Description",
        "Report_TestRunData_TestRun_EndDate" ,
        "Report_TestRunData_TestRun_ActualDuration",
        "Report_TestRunData_TestRun_IsAttachments" ,
        "Report_TestRunData_TestRun_IsDeleted" ,
        "Report_TestRunData_TestRun_ConcurrencyDate",
        "Report_TestRunData_TestRun_ExecutionStatusName",
        "Report_TestRunData_TestRun_TesterName",
        "Report_TestRunData_TestRun_ReleaseName",
        "Report_TestRunData_TestRun_ReleaseVersionNumber",
        "Report_TestRunData_TestRun_TestSetName",
        "Report_TestRunData_TestRun_TestRunTypeName",
        "Report_TestRunData_TestRun_ProjectId",
        "Report_TestRunData_TestRun_ChangeSetId",
        "Report_TestRunData_TestRun_ArtifactPrefix",
        "Report_TestRunData_TestRun_ArtifactType",
        "Report_TestRunData_TestRun_ArtifactToken",
        "Report_TestRunData_TestRun_ArtifactId",
        "Report_TestRunData_TestRun_Properties"
    ],
    
    'test_set_release_wise' : [

    ]
}